# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/VivadoProject/gomoku/gomoku.srcs/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xci
# IP: The module: 'mb_usb_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/VivadoProject/gomoku/gomoku.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/VivadoProject/gomoku/gomoku.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/VivadoProject/gomoku/gomoku.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/VivadoProject/gomoku/gomoku.srcs/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xci
# IP: The module: 'mb_usb_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/VivadoProject/gomoku/gomoku.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/VivadoProject/gomoku/gomoku.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/VivadoProject/gomoku/gomoku.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
